util.AddNetworkString( "openRespawnMenu" )
util.AddNetworkString( "RespawnActivate" )
util.AddNetworkString( "playIntro" )
util.AddNetworkString( "sbFlags" )
util.AddNetworkString( "sbFlagsReturn" )